version: "3.4"
name: projects-app

services:
  postgresql:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build: 
      dockerfile: ./backend/Dockerfile

    volumes:
      - ./backend:/app
    command: /bin/sh -c 'uvicorn main:app --reload --port=5001 --host=0.0.0.0'
    ports:
      - "5001:5001"

    stdin_open: true
    tty: true

volumes:
  pgdata: