version: "3.4"
name: projects-app

services:
  postgresql:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db-test
    ports:
      - "5431:5431"
    volumes:
      - ./postgresql-test:/var/lib/postgresql/data
  
  backend:
    env_file:
      - ./.env
    build:
      dockerfile: ./backend/Dockerfile

    volumes:
      - ./backend:/backend
    command: /bin/sh -c 'uvicorn main:app --reload --port=5001 --host=0.0.0.0  --log-config=log_conf.yaml'
    ports:
      - "5001:5001"

    stdin_open: true
    tty: true

volumes:
  pgdata: