"""empty message

Revision ID: f77c284f64e1
Revises: 6b02984ab58b
Create Date: 2024-03-14 09:05:01.184886

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f77c284f64e1"
down_revision: Union[str, None] = "6b02984ab58b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("project", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "updated_at")
    op.drop_column("project", "created_at")
    # ### end Alembic commands ###
